#Program that reads data from the keyboard and returns its primitive type and all possible information about it and show what the user typed at the end using format()
a = input( 'Type something:' )
print( 'The primitive type:',type(a) )
print( 'Its a number?', a.isnumeric() )
print( 'Its a letter?', a.isalpha() )
print( 'Its alphanumeric?', a.isalnum() )
print( 'Only spaces were entered?', a.isspace() )
print( 'Are upercase letters?', a.isupper() )
print( 'Are lowercase?', a.islower() )
print('Are capital(upercase and lowercase ?', a.istitle() )
print( 'The user typed:', a )