#program that reads data from the keyboard and returns its primitive type and all possible information about it and show what the user typed at the end using format()
a = input( 'Type something:' )
print( 'The primitive type:',type(a))
print( 'Its a number?', s.isnumeric() )
print( 'Its a letter?', s.isalpha() )
print( 'Its alphanumeric?', s.isalnum())
print( 'Only spaces were entered?', s.isspace())
print( 'Are upercase letters?', s.isupper())
print( 'Are lowercase?', s.islower())
print('Are capital(upercase and lowercase ?', s.istitle())
print( 'The user typed:', a )